# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: trusty
sudo: false  

addons:
  apt:
    packages:
    - python-matplotlib 
    - python-tk
    - python-numpy 
    - python-scipy 
    - python-lxml
    - libhdf5-7
    - python-tables

language: python
python: 2.7

virtualenv:
system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=jNeuroML_PyNN_NEURON
    - OMV_ENGINE=jNeuroML_Brian2

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - pip install scipy # Why is this needed? Doesn't seem to get installed correctly on trusty with addons above...
    - pip install tables # Ditto

script:
    - omv all -V
    
    
    

