# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=jNeuroML_NetPyNE

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - pip install scipy
    - pip install tables

script:
    - omv all -V
    
    
    

